name: Teste Workflow

on:
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Mostrar arquivos
        run: ls
